sudo: required
dist: trusty
language: python
python:
  - 2.7
env:
  global:
  - VIRTUALENV_PATH=/home/travis/virtualenv/python2.7
install:
- "pip install -r requirements.txt"
script:
- make travis
group: deprecated-2017Q2
